# Diezel alexa-concierge

# Local Spring Boot Configuration
spring:
  profiles:
    active: local   # For local machine execution configuration.

  # Security
  security:
    basic:
      enabled: false

  # Application Information
  application:
    name: alexa-concierge

  # Database
  datasource:
    # H2
    url: "jdbc:h2:file:~/testDB"
    username: "sa"
    password: ""
    driver-class-name: "org.h2.Driver"

  h2:
    console:
      enabled: true
      path: "/h2"

  jpa:
    hibernate:
      ddl-auto: "update"    # none, update, create, create-drop
    show-sql: true       # Logs SQL as its executed by JPA. Set org.hibernate logging level to INFO.

server:
  port: 4150

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"
  level:
    com.diezel: TRACE
    org.springframework.web: INFO
    org.hibernate: INFO

management:
  security:
    enabled: false      # Disable to access actuator endpoints without requiring authentication.

alexa-concierge:
  integration:
    google:
      geocoding:
        apiEndpoint: https://maps.googleapis.com/maps/api/geocode/outputFormat?parameters
        apiKey: AIzaSyDWSbjeTUUyAp63Ibz6RvR2cNmIRCDTeXU                                     # Generated 4/22/18
  security:
    enabled: false